# 框架备注
port: 40004

# 环境配置
env: dev

# 测试数据库
dev-database:
  host: localhost
  port: 3306
  dbName: project
  userName: root
  password: Wucongxing1..
  mysql-debug: true # 数据库打印
  mysql-max-idle-cons: 5 # 数据库最小连接数
  # 数据库最大连接数
  mysql-max-open-cons: 20

# 正式数据库
master-database:
  host: localhost
  port: 3306
  dbName: project
  username: root
  password: Wucongxing1..
  mysql-debug: true # 数据库打印
  mysql-max-idle-cons: 5 # 数据库最小连接数
  # 数据库最大连接数
  mysql-max-open-cons: 20

# 测试redis
dev-redis:
  host: localhost
  port: 6379
  password: Wucongxing1..
  pool-size: 100

# 限流配置
rate-limit:
  fill-interval: 1 # 填充间隔时间 s为最小单位
  capacity: 100 # 容量

# jwt配置
jwt:
  sign-key: 123456 # 私钥
  bearer: false # 是否使用Bearer头
